PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?eserName ?gamName
WHERE {
  ?eser rdf:type ?eserClass .
  FILTER(STRAFTER(STR(?eserClass), "#") = "HuzunluEser")
  
  ?eser ?gamProp ?gam .
  FILTER(STRAFTER(STR(?gamProp), "#") = "gamKullanir")
  
  BIND(STRAFTER(STR(?eser), "#") AS ?eserName)
  BIND(STRAFTER(STR(?gam), "#") AS ?gamName)
}